version: "2.4"
services:
  elastic-search:
    container_name: elastic-search
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
      
